// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLCpfM2cg5AEgd4CWXgw7Ud3pVTHSPsU',
    appId: '1:813617140631:web:aef1f3a844e4882a2baad2',
    messagingSenderId: '813617140631',
    projectId: 'kisi-kisi-uts-2026',
    authDomain: 'kisi-kisi-uts-2026.firebaseapp.com',
    databaseURL: 'https://kisi-kisi-uts-2026-default-rtdb.firebaseio.com',
    storageBucket: 'kisi-kisi-uts-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHtsF96Jd2U6o1JGge5DrZxumqIU_V9A',
    appId: '1:813617140631:android:f5278dda242636e72baad2',
    messagingSenderId: '813617140631',
    projectId: 'kisi-kisi-uts-2026',
    databaseURL: 'https://kisi-kisi-uts-2026-default-rtdb.firebaseio.com',
    storageBucket: 'kisi-kisi-uts-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVLCpfM2cg5AEgd4CWXgw7Ud3pVTHSPsU',
    appId: '1:813617140631:web:ea42d22a7a3fdf762baad2',
    messagingSenderId: '813617140631',
    projectId: 'kisi-kisi-uts-2026',
    authDomain: 'kisi-kisi-uts-2026.firebaseapp.com',
    databaseURL: 'https://kisi-kisi-uts-2026-default-rtdb.firebaseio.com',
    storageBucket: 'kisi-kisi-uts-2026.firebasestorage.app',
  );

}